# Generated by Django 4.2.16 on 2024-11-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='image',
            field=models.ImageField(upload_to='imagens/'),
        ),
    ]
