# Generated by Django 4.2.16 on 2024-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_alter_projetos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='linkProject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
